config/routes.rb
Depot2::Application.routes.draw do
  resources :devices do 
  	get :qrcode, on: :member
  	put :update_status_taken, on: :member
  end
  root 'devices#index'
end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy, :qrcode]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
    @device = Device.new
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    @device.save
    # respond_to do |format|
    #   if @device.save
    #     format.html { redirect_to root_path, notice: 'Device was successfully created.' }
    #     format.json { render action: 'show', status: :created, location: @device }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @device.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    @device.update(device_params)
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  def qrcode
  end

  def update_status_taken
    @device = Device.find_by(serial_number: params[:id]);
    @device.taken = !@device.taken
    @device.user = params[:device][:user]
    @device.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :version, :model, :serial_number, :user, :taken)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/devices/_device.html.erb
<tr class="<%= device.serial_number %>">
  <!-- <td><%= link_to device.name, device_path(device) %></td> -->
  <td><%= device.name %></td>
  <td><%= device.model %></td>
  <td><%= device.serial_number %></td>
  <td class="user"> <%= device.user %> </td>
  <td class="reserve"> <%= device.taken %> </td>
  <td class="qrcode"><%= link_to 'Get QR', qrcode_device_path(device), class: "btn btn-success btn-lg", remote: true %></td>
<!--   <td><%= link_to 'Show', device %></td>
  <td><%= link_to 'Edit', edit_device_path(device) %></td> -->
  <!-- <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
</tr>

app/views/devices/_new_device_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@device,remote: true) do |f| %>
          <% if @device.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

              <ul>
              <% @device.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :version %><br>
            <%= f.text_field :version %>
          </div>
          <div class="field">
            <%= f.label :model %><br>
            <%= f.text_field :model %>
          </div>
          <div class="field">
            <%= f.label :serial_number %><br>
            <%= f.text_field :serial_number %>
          </div>
          <div class="field">
            <%= f.label :user %><br>
            <%= f.text_field :user %>
          </div>
          <div class="field">
            <%= f.label :taken %><br>
            <%= f.check_box :taken %>
          </div>

      </div>
      <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <%= f.submit "Create", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/devices/create.js.erb
$("#myModal").modal('hide');
$("table").append("<%= escape_javascript(render @device) %>");

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p>
  <table class='table'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Model</th>
        <th>Serial number</th>
        <th>User</th>
        <th>Taken</th>
        <th>QR Device</th>
      </tr>
    </thead>
     <tbody>
      <%= render @devices %>
    </tbody>
  </table>
</p>
<br>


<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" id="js-new-device">New Device</button>

<%= render 'new_device_modal' %>

app/views/devices/index.html_backup.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Version</th>
      <th>Model</th>
      <th>Serial number</th>
      <th>User</th>
      <th>Taken</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.version %></td>
        <td><%= device.model %></td>
        <td><%= device.serial_number %></td>
        <td><%= device.user %></td>
        <td><%= device.taken %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/qrcode.js.erb
var serial_number = encodeURIComponent('{"serial_number": "<%= @device.serial_number%>" }');
$("#qrCodeContainer").html("<img src='https://chart.googleapis.com/chart?chs=375x375&cht=qr&chl=" + serial_number + "'/>");

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @device.version %>
</p>

<p>
  <strong>Model:</strong>
  <%= @device.model %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @device.serial_number %>
</p>

<p>
  <strong>User:</strong>
  <%= @device.user %>
</p>

<p>
  <strong>Taken:</strong>
  <%= @device.taken %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/devices/update.js.erb
$(".<%= @device.serial_number %> .reserve").text("<%= @device.taken %>");
$(".<%= @device.serial_number %> .user").text("<%= @device.user %>");
$(".<%= @device.serial_number %>").addClass("hightlight");
setTimeout(function() {
	$(".<%= @device.serial_number %> ").removeClass("hightlight");
}, 2000);

app/views/devices/update_status_taken.js.erb
$("#nameModal").modal('hide');
$(".<%= @device.serial_number %> .reserve").text("<%= @device.taken %>");
$(".<%= @device.serial_number %> .user").text("<%= @device.user %>");
$(".<%= @device.serial_number %>").addClass("hightlight");
setTimeout(function() {
	$(".<%= @device.serial_number %> ").removeClass("hightlight");
}, 2000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body onload="load()">

	<div class="container">
		
		<div class="container" id="webcamContainer">
			<div id="outdiv">
			</div>
		</div>
		<div id="qrCodeContainer"></div>
		
		<canvas id="qr-canvas" width="500" height="375"></canvas>
		
		<%= yield %>

		<div class="modal fade" id="nameModal">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        <h4 class="modal-title">Modal title</h4>
		      </div>
		      <div class="modal-body">
			      <div class="form-group">
				    <label for="exampleInputEmail1">Name</label>
				    <input type="text" class="form-control js-name" id="nameINput" placeholder="Enter Name">
				  </div>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		        <button type="button" class="btn btn-primary js-submit">Submit</button>
		      </div>
		    </div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->
		
	</div>


</body>
</html>